### ISSUE TITLE
Cannot pass Windows Phone 8.1 WinRT app certification

### ISSUE THREAD

**Issue by zipswich** [cureos/aforge#14]
I have just tried the NuGet package by including it in an app, but without using any function. Windows App Certification Kit fails to certify the package built with this.  The error message is the following: 

Error Found: The supported APIs test detected the following errors:
◦This API is not supported for this application type - Api=memcpy. Module=ntdll.dll. File=AForge.dll.
◦This API is not supported for this application type - Api=memset. Module=ntdll.dll. File=AForge.dll.

**Comment by anders9ustafsson** [comment]
@zipswich Many thanks for reporting this issue, I have not been aware of this app certification limitation for WPA 8.1. I will deal with this as soon as possible and publish an update that will allow you to circumvent this problem.

**Comment by zipswich** [comment]
@anders9ustafsson  Thanks a lot for the response at a lightning speed. Does the fix mean that the package does not support WP?

**Comment by anders9ustafsson** [comment]
@zipswich I have not updated the NuGet packages yet, I might look into another issue first before I do that. But don't worry WPA 8.1 (i.e. non-Silverlight Windows Phone) is still supported. It is just that you will use the PCL profile 111 version (.NET 4.5 + Windows 8 + Windows Phone 8.1) of *AForge.Core* instead, and that particular version does not call NTDLL.dll.

**Comment by zipswich** [comment]
Thanks for the clarification.

**Comment by anders9ustafsson** [comment]
@zipswich I have now updated the NuGet packages. Please give them a spin to see if it works better this time. It is probably a good idea to unload and reload *AForge.Core* since it has changed platform targets in this release.

**Comment by zipswich** [comment]
Hallelujah!  The app package built with the NuGet package has passed the test of Windows App Certification Kit.  Thanks a lot.  At this point of time, I am looking for motion functionality.  I assume I need to use portable AForge.Vision too.

**Comment by anders9ustafsson** [comment]
Depending what you are looking for, motion can be a more difficult issue. I have not (yet) been able to adapt the *AForge.Video...* libraries sufficiently to PCL. But please check if the functionality in *AForge.Vision* (and for that matter, *Accord.Vision*) is enough for you.

**Comment by zipswich** [comment]
Thank you for the tips.  I saw your name on the creators of Portable AForge Vision which I assume has motion detection.  I have just started looking into AForge, and am still trying to figure out which packages offer what functions.
