### ISSUE TITLE
Recalculating chromosome with new seed

### ISSUE THREAD

**Issue by SvenPetroll** [cureos/aforge#18]
To compare the fitness of each chromosome, I use a seed to make sure the random elements stay the same. For every generation a new seed is used, but since some (~15/100 for RouletteSelection) Chromosomes in the population are only cloned, they effectively can't be compared to the mutated Chromosomes.

Is there an option to reset the fitness of every Chromosome?

**Comment by anders9ustafsson** [comment]
@SvenPetroll I am not very experienced with the innings of the *Genetic* library; my main contribution has been to port the *AForge* libraries to PCL. You might have a better chance of getting a valid response if you post this question on the [AForge.NET Framework Forum](http://www.aforgenet.com/aforge/forum/viewforum.php?f=2).
