### ISSUE TITLE
Unable to build Xamarin Classic with registered version shims

### ISSUE THREAD

**Issue by kmikhai** [cureos/aforge#19]
Only fails when we replace Shim.Drawing.dll with licensed versions 

Error 68
The "LinkAssemblies" task failed unexpectedly.
Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item 'System.Drawing.Graphics System.Drawing.Graphics::FromImage(System.Drawing.Bitmap)' (defined in 'AForge.Imaging, Version=2.2.5.0, Culture=neutral, PublicKeyToken=ba8ddea9676ca48b') from 'AForge.Imaging, Version=2.2.5.0, Culture=neutral, PublicKeyToken=ba8ddea9676ca48b' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Drawing.Graphics System.Drawing.Graphics::FromImage(System.Drawing.Bitmap)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   --- End of inner exception stack trace ---
   at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()
ACS.FundRaising.Android

Fails with the following 

 

<img width="387" alt="error1" src="https://cloud.githubusercontent.com/assets/12633924/9686576/381f7e42-52ea-11e5-8452-8104a9f724ef.png">

Does not fail with:

<img width="369" alt="error2" src="https://cloud.githubusercontent.com/assets/12633924/9686578/3c0e47c2-52ea-11e5-842c-5d2638c56e5a.png">

**Comment by anders9ustafsson** [comment]
@kmikhai Thanks for this thorough report! I will look into this issue as soon as possible.

Regards,
Anders @ Cureos

**Comment by kmikhai** [comment]
Hi. Any updates or additional info we need to provide? This sort of leaves us unable to produce a licensed production build. The issue does not appear to exist with unlicensed dll's

**Comment by anders9ustafsson** [comment]
I will try to look into the issue tomorrow when I have full access to a build host. Are you sure that the issue is limited to the "full" DLLs? And you are using the Classic API?

**Comment by kmikhai** [comment]
a) yes the issue only appears when we try to replace the nuget provided shim dll's with licensed versions

b) Yes we're using Xamarin Classic, MVVMCross.

**Comment by anders9ustafsson** [comment]
@kmikhai I have now made a fix in the *Shim* library of an issue that I suspect has been causing your build failure. Please update *Shim* to the latest version (1.0.2.50909) and let me know if your build problems are solved or remain.

**Comment by kmikhai** [comment]
Hi. Where do we get the licensed version of the updated shims? Last time when we purchased the license it was through a one drive link

Sent from my iPhone

On Sep 9, 2015, at 4:26 AM, Anders Gustafsson <notifications@github.com<mailto:notifications@github.com>> wrote:


@kmikhai<https://github.com/kmikhai> I have now made a fix in the Shim library of an issue that I suspect has been causing your build failure. Please update Shim to the latest version (1.0.2.50909) and let me know if your build problems are solved or remain.

-
Reply to this email directly or view it on GitHub<https://github.com/cureos/aforge/issues/19#issuecomment-138852608>.

Mike Katchourine | Director, Common Integration Services
American Cancer Society, Inc.
8400 Silver Crossing
Oklahoma City, OK 73132
Phone: 405.782.1112
cancer.org<http://www.cancer.org> | 1.800.227.2345

This message (including any attachments) is intended exclusively for the individual to whom it is addressed and may contain proprietary, protected, or confidential information. If you are not the named addressee, you are not authorized to read, print, copy, or disseminate this message or any part of it. If you have received this message in error, please notify the sender immediately.

**Comment by anders9ustafsson** [comment]
If you have the link available, it should still work for you. If you do not, please e-mail me at licenses@cureos.com and I'll forward the link again.
